from hypothesis import given
from hypothesis import strategies as st

from src.agents.base import AgentResult
from src.models.finding import Finding, FindingSeverity
from src.orchestrator.pipeline import PipelineOrchestrator, _build_findings_summary
from tests.conftest import findings


# ---------------------------------------------------------------------------
# Property 27a: Finding structure validity
# ---------------------------------------------------------------------------


@given(finding=findings())
def test_finding_has_all_required_nonempty_fields(finding: Finding) -> None:
    """**Validates: Requirements 24.1**

    Any Finding generated by the findings() strategy has all required
    non-empty fields: severity is a valid FindingSeverity, and
    stage/construct/message/recommended_action are non-empty strings.
    """
    assert isinstance(finding.severity, FindingSeverity)
    assert finding.severity in list(FindingSeverity)
    assert isinstance(finding.stage, str) and len(finding.stage) >= 1
    assert isinstance(finding.construct, str) and len(finding.construct) >= 1
    assert isinstance(finding.message, str) and len(finding.message) >= 1
    assert isinstance(finding.recommended_action, str) and len(finding.recommended_action) >= 1


# ---------------------------------------------------------------------------
# Property 27b: Finding serialization round-trip
# ---------------------------------------------------------------------------


@given(finding=findings())
def test_finding_serialization_round_trip(finding: Finding) -> None:
    """**Validates: Requirements 24.1**

    Any Finding can be serialized to dict via .model_dump() and
    deserialized back via Finding(**d) producing an equal object.
    """
    dumped = finding.model_dump()
    restored = Finding(**dumped)
    assert restored == finding
    assert restored.severity == finding.severity
    assert restored.stage == finding.stage
    assert restored.construct == finding.construct
    assert restored.message == finding.message
    assert restored.recommended_action == finding.recommended_action


# ---------------------------------------------------------------------------
# Property 27c: Finding summary correctness
# ---------------------------------------------------------------------------


@given(finding_list=st.lists(findings(), max_size=20))
def test_findings_summary_counts_match(finding_list: list[Finding]) -> None:
    """**Validates: Requirements 24.1**

    For any list of Findings, _build_findings_summary() returns a dict
    where the sum of all values equals the length of the input list,
    and every severity present in the input appears as a key.
    """
    summary = _build_findings_summary(finding_list)

    assert sum(summary.values()) == len(finding_list)

    severities_present = {f.severity.value for f in finding_list}
    for sev in severities_present:
        assert sev in summary
        assert summary[sev] >= 1


# ---------------------------------------------------------------------------
# Property 27d: Finding accumulation from manifest with .findings attribute
# ---------------------------------------------------------------------------


@given(finding_list=st.lists(findings(), min_size=1, max_size=10))
def test_accumulate_findings_collects_from_findings_attribute(
    finding_list: list[Finding],
) -> None:
    """**Validates: Requirements 24.1**

    When a manifest-like object has a .findings attribute containing
    Finding objects, _accumulate_findings() collects all of them into
    the accumulated list.
    """

    class _ManifestStub:
        def __init__(self, findings: list[Finding]) -> None:
            self.findings = findings

    stub = _ManifestStub(finding_list)
    result = AgentResult(
        agent_name="test_agent",
        artifacts={"some_manifest": stub},
    )

    accumulated: list[Finding] = []
    context: dict = {"accumulated_findings": accumulated}
    PipelineOrchestrator._accumulate_findings(
        "test_agent", result, accumulated, context,
    )

    assert len(accumulated) == len(finding_list)
    for original in finding_list:
        assert original in accumulated
